rocm: add reason for disabled component
icl-utk-edu/papi pull request #219
Opened 2024-08-21 20:04 UTC by dbarry9

## Pull Request Description
Previously, in the absence of a ROCm device, the rocm component did not set the string containing the reason that the component was disabled.

These changes have been tested using ROCm 6.2

## Author Checklist
- [ ] **Description**
_Why_ this PR exists. Reference all relevant information, including _background_, _issues_, _test failures_, etc
- [ ] **Commits**
_Commits_ are self contained and only do one thing
_Commits_ have a header of the form: `module: short description`
_Commits_ have a body (whenever relevant) containing a detailed description of the addressed problem and its solution
- [ ] **Tests**
The PR needs to pass all the tests

2024-08-21 21:04 UTC, Treece-Burgess approved these changes
I personally would add a format specifier to `snprintf`, but I don't believe it is actually necessary in this case or beneficial since we are providing the error message. 

The rest of the file seems to follow suit with no format specifier when we directly provide the error message as well.

2025-02-26 02:35 UTC, Treece-Burgess requested changes

2025-02-26 02:35 UTC, Treece-Burgess commented on src/components/rocm/roc_common.c
> +        snprintf(error_string, PAPI_MAX_STR_LEN, "Call to hsa_init() failed.");
Two things:

- The format specifier is missing
- I would check the return value of `snprintf` as an additional safety net e.g: 
```
int len = snprintf(error_string, PAPI_MAX_STR_LEN, "%s", "Call to hsa_init() failed.");
if (len < 0 || len >= PAPI_MAX_STR_LEN) {
    SUBDBG("Failed to write error string.\n");
}
```

2025-02-26 02:35 UTC, Treece-Burgess commented on src/components/rocm/rocm.c
> -    strcpy(_rocm_vector.cmp_info.disabled_reason, "");
Why remove this line?

2025-02-26 18:05 UTC, dbarry9 commented on src/components/rocm/rocm.c
> -    strcpy(_rocm_vector.cmp_info.disabled_reason, "");
This line was overwriting the error message with an empty string; I am not sure why it was here.

2025-02-26 18:39 UTC, dbarry9 commented on src/components/rocm/roc_common.c
> +        snprintf(error_string, PAPI_MAX_STR_LEN, "Call to hsa_init() failed.");
I have updated the PR according to this feedback.

2025-04-19 15:45 UTC, Treece-Burgess approved these changes
I have verified the behavior on a machine with and without ROCm devices using ROCm 6.3.2.

Without:
```
./papi_component_avail
Name:   rocm                    GPU events and metrics via AMD ROCm-PL API
   \-> Disabled: Call to hsa_init() failed. This could be due to ROCm devices failing to be detected.

```
```
Application code test with PAPI_get_component_info:
Disabled reason: Call to hsa_init() failed. This could be due to ROCm devices failing to be detected.
Disabled: -14
Initialized: 0
```

With (1 * MI210):
```
./papi_component_avail
Name:   rocm                    GPU events and metrics via AMD ROCm-PL API
                                Native: 412, Preset: 0, Counters: 412
```
```
Application code test with PAPI_get_component_info:
Disabled reason: 
Disabled: 0
Initialized: 1
```

2025-04-19 15:45 UTC, merged