PR author's checklist
icl-utk-edu/papi pull request #26
Opened 2023-06-20 12:18 UTC by gcongiu

Add PR author's checklist for github

2023-06-20 12:19 UTC, gcongiu commented
@jagode @adanalis @anustuvicl @dbarry9 anything you would like to add the the checklist?

2023-06-20 13:32 UTC, dbarry9 commented
The list looks good to me.

`The PR needs to pass all the tests.`

I know that some tests can fail if they take too long (e.g. > 60 minutes). This happened to one of my PR's with the ROCM test. I am not sure the cause of this, but this is a reason a test might not pass, through no fault of the PR author.

2023-06-20 13:35 UTC, gcongiu commented
@dbarry9 generally, all the tests should pass. If some don't we can evaluate whether to merge anyway or not on a case basis (like you said).

2023-06-20 13:43 UTC, dbarry9 commented
I agree.

2023-06-20 14:06 UTC, gcongiu commented
@G-Ragghianti we might not want to run tests for PRs like this one. Is there a way of triggering tests on demand with GitHub actions, e.g., by adding a comment to the PR?

2023-06-20 14:45 UTC, G-Ragghianti commented
There is a way, but I would prefer to run a few occasional tests
unnecessarily rather than turn off automated testing.

On Tue, Jun 20, 2023 at 4:07 PM Giuseppe Congiu ***@***.***>
wrote:

> @G-Ragghianti <https://github.com/G-Ragghianti> we might not want to run
> tests for PRs like this one. Is there a way of triggering tests on demand
> with GitHub actions, e.g., by adding a comment to the PR?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/icl-utk-edu/papi/pull/26#issuecomment-1598866492>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH7Q5Y7GJV4NYYT6LEQ6CKLXMGVARANCNFSM6AAAAAAZNGI6IA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-20 14:58 UTC, gcongiu commented
@G-Ragghianti ok let's keep it this way. We can always change the default in the future if the need arises.

2023-06-23 21:49 UTC, jagode commented on .github/pull_request_template.md
> +- [ ] **Description**
Checklist for Pull Request Authors

2023-06-23 21:51 UTC, jagode commented on .github/pull_request_template.md
> +_Why_ this PR exists. Reference all relevant information including _background_, _issues_, _test failures_, etc
Include _Why_ this PR exists. 
(Comma after 'information')

2023-06-23 21:52 UTC, jagode commented on .github/pull_request_template.md
> +_Commits_ have header of the form: `module: short description`
a header

2023-06-23 21:53 UTC, jagode commented on .github/pull_request_template.md
> +_Commits_ have body (whenever relevant) containing detailed description of the addressed problem and its solution
a body...
a detailed...

2023-06-23 21:57 UTC, jagode requested changes
I would make it a little bit more descriptive to enhance readability. See suggestions inline.

2023-06-26 07:13 UTC, gcongiu commented on .github/pull_request_template.md
> +_Commits_ have header of the form: `module: short description`
done

2023-06-26 07:13 UTC, gcongiu commented on .github/pull_request_template.md
> +_Commits_ have body (whenever relevant) containing detailed description of the addressed problem and its solution
done

2023-06-27 12:19 UTC, gcongiu commented
@jagode I update the PR

2023-07-03 15:31 UTC, jagode approved these changes
Looks good now.

2023-07-03 15:31 UTC, merged