powercap: ignore the psys entry
icl-utk-edu/papi pull request #53
Opened 2023-07-20 21:38 UTC by iskra-anl

This is a bit of a workaround for newer Intel CPUs that, in addition to the traditional "package-<n>" entries in /sys/class/powercap/, also contain a "psys" entry that controls the platform domain (see, e.g., https://lkml.kernel.org/lkml/1458516392-2130-3-git-send-email-srinivas.pandruvada@linux.intel.com/).

PAPI currently assumes that entries starting with "intel-rapl:0" correspond to socket 0 and "intel-rapl:1" to socket 1.  With "psys" around that unfortunately need not be the case; on at least one system relevant to DOE (I can't post the details as it's not public yet) intel-rapl:0 corresponds to socket 0, intel-rapl:1 corresponds to *psys*, and intel-rapl:2 corresponds to socket 1 (what a mess!).  What currently happens is that PAPI entirely misses the counters for socket 1.

This PR works around the problem by exhaustively searching for the right "intel-rapl:<n>" directory.  It preserves the current PAPI assumption that ZONE0 events correspond to socket 0 and ZONE1 to socket 1.  On the other hand, it completely ignores the "psys" entry, while one could argue that the data it contains should ideally be made available as well...

I also included a somewhat related fix to check that the files inside /sys/class/powercap/intel-rapl:<n> directories not only exist, but are readable.  On recent Linux kernels, "energy_uj" is by default readable by root only, which is something that PAPI fails to detect, resulting in 0 being returned for that counter without any indication of a problem. That seemed like an error to me but I actually don't know what PAPI's policy is on counters that exist but are unreadable by the current user.

## Pull Request Description

## Author Checklist
- [] **Description**
_Why_ this PR exists. Reference all relevant information, including _background_, _issues_, _test failures_, etc
- [ ] **Commits**
_Commits_ are self contained and only do one thing
_Commits_ have a header of the form: `module: short description`
_Commits_ have a body (whenever relevant) containing a detailed description of the addressed problem and its solution
- [ ] **Tests**
The PR needs to pass all the tests

2023-07-24 17:44 UTC, gcongiu requested changes
@iskra-anl this looks good to me. Only have a nitpick concerning splitting the commit into two separate commits.

2023-07-25 20:25 UTC, iskra-anl commented on src/components/powercap/linux-powercap.c
> +        if (access(event_path, R_OK) == -1) { continue; }
Just to clarify, would you like that to be a separate PR or merely a separate commit within a single PR?

2023-07-26 06:39 UTC, gcongiu commented on src/components/powercap/linux-powercap.c
> +        if (access(event_path, R_OK) == -1) { continue; }
Just a separate commit is fine. No need to create a new PR.

2023-07-26 20:48 UTC, iskra-anl commented on src/components/powercap/linux-powercap.c
> +        if (access(event_path, R_OK) == -1) { continue; }
Should be done now.

2023-07-27 08:22 UTC, gcongiu approved these changes

2023-07-28 14:33 UTC, merged