cuda: Improve CUDA component PAPI_read() overhead, issue 85
icl-utk-edu/papi pull request #99
Opened 2023-10-06 18:02 UTC by anustuvicl

- Improves overhead from 15000ms to 2200ms for 100 PAPI_read() calls
- Improves speed of `papi_native_avail` utility
- Improvements over old component
    - PAPI_start() correctly resets counter values
    - Measurements consistent across reads

2023-10-09 15:34 UTC, gcongiu requested changes
This commit is too hard to review. Please split it into simpler commits

2023-10-09 15:34 UTC, gcongiu commented on src/components/cuda/cupti_profiler.c
> +typedef NVPW_CUDA_MetricsContext_Create_Params MCCP_t;
I think this adds nothing and makes code harder to read.

2023-10-09 15:34 UTC, gcongiu commented on src/components/cuda/cupti_profiler.c
> +static int nvpw_cuda_metricscontext_create(cuptip_control_t state);
This is static no need for name spacing

2023-10-09 22:00 UTC, anustuvicl commented
I already merged it from several commits into one. I dont have the original history due to force push. Please try to review as one commit.

2023-10-10 14:12 UTC, gcongiu approved these changes
Please rebase onto master before merging

2023-10-18 16:51 UTC, merged